# Если нашли баг, или что-то хотите увидеть в плагине, можете написать мне в Discord; shved255
# Настройки дискорд-бота.
Discord:
  # Токен бота который берется с https://discord.com/developers/applications/. Писать без кавычек.
  Token: 
  # Титл главного сообщения бота.
  Title: "Верификация"
  # Описание главного сообщения.
  Description: "Нажмите на кнопку ниже и отправьте запрос, чтобы пройти\n
        верификацию на бота, не бойтесь,\n
        если вы не пройдете проверку, то не выдадут бан!"
  # Основной цвет у бота в дискорде. Цвет Указывается в формате HEX, только в начале указывайте 0x вместо #. 
  Color: 0x6122E6
  # Если бот отвечает и работает стабильно, напишется это сообщение.
  SuccessSendPacket: "Запрос на верификацию был успешно отправлен!"
  # Если игрок не онлайн или неправильно введён ник. 
  PlayerNotOnline: "Игрок не найден!"
  # Если игрок уже проходил проверку и он есть в базе. База - система айпи, то есть если игрок уже проходил проверку и его IP есть в players.yml, то если он попытается сделать верификацию своего ника выведется это сообщение.
  PlayerInBase: "Игрок уже проходил проверку!"
  # Если проверка успешно пройдена, игрок онлайн и игрока не было в базе.
  PlayerSuccessDiscord: "Проверка успешно пройдена!"
  # Если игрок ввёл неправильный код который ему выдавалсяя изначально.
  WrongMessage: "Неправильный код!"
# Настройки в майнкрафте. 
Minecraft:
  # Время в часах скоолько не нужно будет проходить проверку. В данном случае 72 часа = 3 дня. Если хотите отключить - вписывайте 0.
  HoursTime: 72
  # Время, сколько будет у игрока на проверку.
  Time: 120
  # Включить ли таймер секунд до конца проверка на шкале опыта? ВНИМАНИЕ!!! Если Вы используете на игровом сервере, желательно выключить. Потому что будет пропадать опыт у игроков после проверки. True || false
  LevelEnable: false
  # Если игрок не успел пройти проверку в течении задонного времени. Есть поддержка цветов.
  KickMessage: "&8&o&nВы провалили проверку, возможно Вы &f&o&lбот&8&o&n&n."
  # Сообщение, которое пишет игрок во время проверки. Также есть поддержка цветов, есть плейсхолдер {TIME} который показывает время игрока, сколько у него осталось времени. {CODE} заменяет на код игрока.
  Message: "&fПройдите проверку через нашего Дискорд Бота. Перейдите по ссылке https://discord.gg/example и найдите бота с именем Верификация. И напишите ему /верификация, введите код и свой ник. У Вас есть &c{TIME} &fсекунд. Ваш код: &C{CODE}&f."
  # Сообщение, если игрок прошел проверку успешно. Работают цвета.
  SuccessMessage: "&aВы прошли проверку!"  
  # Команды выполняемые от имени игрока. Также работают если игрок уже находится в базе айпи. Также если Вам нужно ввести больше комманд, пишите через запятую.
  PlayerCommands: []
  # Команды выполняемые от имени сервера. Используйте %PLAYER% чтобы использовать ник игрока который прошел проверку. Плейсхолдер работает только в этом конфиге. Пример: [tp %PLAYER% 0 0 0] - Телепортирует игрока на координаты 0 0 0.
  # Также если Вам нужно ввести больше комманд, пишите через запятую. Также работают если игрок уже находится в базе айпи.
  ServerCommands: []
# Настройка БоссБара.  
BossBar:
  # Цвета БоссБара.
  Color: RED # RED, GREEN, BLUE, YELLOW, PURPLE, WHITE, ORANGE
  # Стили БоссБара.
  Style: SOLID # SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  # БоссБар. Также есть поддержка цветов, есть плейсхолдер {TIME} который показывает время игрока, сколько у него осталось времени. {CODE} заменяет на код игрока.
  BossBarInfo: "&fЭто проверка, у Вас для верефикации есть &c{TIME} &fсекунд. Ваш код: &c{CODE}&f."  